@startuml

title __APP's Class Diagram__\n

  namespace com.taobao.android.mnn {
    enum MNNForwardType {
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNImageProcess {
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNNetInstance {
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNNetNative {
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNPortraitNative {
    }
  }
  

  namespace com.taobao.android.mnn {
    namespace emo {
      class com.taobao.android.mnndemo.BuildConfig {
      }
    }
  }
  

  namespace com.taobao.android.mnn {
    namespace emo {
      class com.taobao.android.mnndemo.CameraView {
      }
    }
  }
  

  namespace com.taobao.android.mnn {
    namespace emo {
      class com.taobao.android.mnndemo.ImageActivity {
      }
    }
  }
  

  namespace com.taobao.android.mnn {
    namespace emo {
      class com.taobao.android.mnndemo.OpenGLTestActivity {
      }
    }
  }
  

  namespace com.taobao.android.mnn {
    namespace emo {
      class com.taobao.android.mnndemo.PortraitActivity {
      }
    }
  }
  

  namespace com.taobao.android.mnn {
    namespace emo {
      class com.taobao.android.mnndemo.VideoActivity {
      }
    }
  }
  

  namespace com.taobao.android.opengl {
    class com.taobao.android.opengl.CameraRenderer {
    }
  }
  

  namespace com.taobao.android.opengl {
    class com.taobao.android.opengl.OESTexture {
    }
  }
  

  namespace com.taobao.android.opengl {
    class com.taobao.android.opengl.Shader {
    }
  }
  

  namespace com.taobao.android.utils {
    class com.taobao.android.utils.Common {
    }
  }
  

  namespace com.taobao.android.utils {
    class com.taobao.android.utils.PermissionUtils {
    }
  }
  

  namespace com.taobao.android.utils {
    class com.taobao.android.utils.PortraitCameraView {
    }
  }
  

  namespace com.taobao.android.utils {
    enum RotateType {
    }
  }
  

  namespace com.taobao.android.utils {
    class com.taobao.android.utils.TxtFileReader {
    }
  }
  

  com.taobao.android.mnndemo.CameraView .up.|> android.hardware.Camera.PreviewCallback
  com.taobao.android.mnndemo.CameraView .up.|> android.view.SurfaceHolder.Callback
  com.taobao.android.mnndemo.CameraView -up-|> android.view.SurfaceView
  com.taobao.android.mnndemo.CameraView o-- com.taobao.android.mnndemo.CameraView.PreviewCallback : mPreviewCallback
  com.taobao.android.mnndemo.ImageActivity .up.|> android.view.View.OnClickListener
  com.taobao.android.mnndemo.ImageActivity -up-|> android.support.v7.app.AppCompatActivity
  com.taobao.android.mnndemo.ImageActivity o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mInputTensor
  com.taobao.android.mnndemo.ImageActivity o-- com.taobao.android.mnn.MNNNetInstance : mNetInstance
  com.taobao.android.mnndemo.ImageActivity o-- com.taobao.android.mnn.MNNNetInstance.Session : mSession
  com.taobao.android.mnndemo.OpenGLTestActivity -up-|> android.support.v7.app.AppCompatActivity
  com.taobao.android.mnndemo.OpenGLTestActivity o-- com.taobao.android.opengl.CameraRenderer : mRenderer
  com.taobao.android.mnndemo.PortraitActivity -up-|> android.support.v7.app.AppCompatActivity
  com.taobao.android.mnndemo.PortraitActivity o-- com.taobao.android.utils.PortraitCameraView : mCameraView
  com.taobao.android.mnndemo.PortraitActivity o-- com.taobao.android.mnn.MNNNetInstance.Config : mConfig
  com.taobao.android.mnndemo.PortraitActivity o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mInputTensor
  com.taobao.android.mnndemo.PortraitActivity o-- com.taobao.android.mnn.MNNNetInstance : mNetInstance
  com.taobao.android.mnndemo.PortraitActivity o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mOutputTensor
  com.taobao.android.mnndemo.PortraitActivity o-- com.taobao.android.mnn.MNNNetInstance.Session : mSession
  com.taobao.android.mnndemo.VideoActivity .up.|> android.widget.AdapterView.OnItemSelectedListener
  com.taobao.android.mnndemo.VideoActivity -up-|> android.support.v7.app.AppCompatActivity
  com.taobao.android.mnndemo.VideoActivity o-- com.taobao.android.mnndemo.CameraView : mCameraView
  com.taobao.android.mnndemo.VideoActivity o-- com.taobao.android.mnn.MNNNetInstance.Config : mConfig
  com.taobao.android.mnndemo.VideoActivity o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mInputTensor
  com.taobao.android.mnndemo.VideoActivity o-- com.taobao.android.mnn.MNNNetInstance : mNetInstance
  com.taobao.android.mnndemo.VideoActivity o-- com.taobao.android.mnn.MNNNetInstance.Session : mSession
  com.taobao.android.opengl.CameraRenderer .up.|> android.graphics.SurfaceTexture.OnFrameAvailableListener
  com.taobao.android.opengl.CameraRenderer .up.|> android.opengl.GLSurfaceView.Renderer
  com.taobao.android.opengl.CameraRenderer -up-|> android.opengl.GLSurfaceView
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.opengl.OESTexture : mCameraTexture
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Config : mConfig
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mInputTensor
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance : mNetInstance
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.opengl.Shader : mOffscreenShader
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mOutputTensor
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Session : mSession
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.opengl.CameraRenderer.MnnThread : mnnThread
  com.taobao.android.utils.PortraitCameraView .up.|> android.hardware.Camera.PreviewCallback
  com.taobao.android.utils.PortraitCameraView .up.|> android.view.SurfaceHolder.Callback
  com.taobao.android.utils.PortraitCameraView -up-|> android.view.SurfaceView
  com.taobao.android.utils.PortraitCameraView o-- com.taobao.android.utils.PortraitCameraView.Config : mConfig
  com.taobao.android.utils.PortraitCameraView o-- com.taobao.android.utils.PortraitCameraView.PreviewCallback : mPreviewCallback
  com.taobao.android.utils.PortraitCameraView o-- com.taobao.android.utils.RotateType : mPreviewRotateType
  com.taobao.android.utils.PortraitCameraView o-- com.taobao.android.utils.PortraitCameraView.CameraSizeComparator : sizeComparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
