@startuml

title __OPENGL's Class Diagram__\n

  namespace com.taobao.android.opengl {
    class com.taobao.android.opengl.CameraRenderer {
        - mCamera : Camera
        - mCameraHeight : int
        - mCameraID : int
        - mCameraWidth : int
        - mContext : Context
        - mHeight : int
        - mOrientationM : float[]
        {static} - mOutputDateReady : boolean
        - mPreviewCB : PreviewCallback
        - mPreviewData : byte[]
        - mPreviewImageBuf : ByteBuffer
        - mRatio : float[]
        - mSurfaceTexture : SurfaceTexture
        - mTextView : TextView
        {static} - mThreadReady : boolean
        - mTransformM : float[]
        - mVertices : ByteBuffer
        - mWidth : int
        - netInputHeight : int
        - netInputWidth : int
        - netOutputHeight : int
        - netOutputWidth : int
        - updateTexture : boolean
        + CameraRenderer()
        + CameraRenderer()
        {static} + findFrontCamera()
        + init()
        + onDestroy()
        + onDrawFrame()
        + onFrameAvailable()
        + onSurfaceChanged()
        + onSurfaceCreated()
        + prepareNet()
        + setContext()
        + setTextView()
        - renderVertices()
    }
  }
  

  namespace com.taobao.android.opengl {
    class com.taobao.android.opengl.CameraRenderer.MnnThread {
        + run()
    }
  }
  

  namespace com.taobao.android.opengl {
    class com.taobao.android.opengl.OESTexture {
        - mTextureHandle : int
        + getTextureId()
        + init()
    }
  }
  

  namespace com.taobao.android.opengl {
    class com.taobao.android.opengl.Shader {
        - fragmentSource : String
        - mProgram : int
        - mShaderFragment : int
        - mShaderHandleMap : HashMap<String, Integer>
        - mShaderVertex : int
        - vertexSource : String
        + Shader()
        + deleteProgram()
        + getHandle()
        + getHandles()
        + programHandle()
        + setProgram()
        + useProgram()
        - loadRawString()
        - loadShader()
    }
  }
  

  com.taobao.android.opengl.CameraRenderer .up.|> android.graphics.SurfaceTexture.OnFrameAvailableListener
  com.taobao.android.opengl.CameraRenderer .up.|> android.opengl.GLSurfaceView.Renderer
  com.taobao.android.opengl.CameraRenderer -up-|> android.opengl.GLSurfaceView
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.opengl.OESTexture : mCameraTexture
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Config : mConfig
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mInputTensor
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance : mNetInstance
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.opengl.Shader : mOffscreenShader
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Session.Tensor : mOutputTensor
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.mnn.MNNNetInstance.Session : mSession
  com.taobao.android.opengl.CameraRenderer o-- com.taobao.android.opengl.CameraRenderer.MnnThread : mnnThread
  com.taobao.android.opengl.CameraRenderer +-down- com.taobao.android.opengl.CameraRenderer.MnnThread


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
