@startuml

title __MNN's Class Diagram__\n

  namespace com.taobao.android.mnn {
    enum MNNForwardType {
      FORWARD_AUTO
      FORWARD_CPU
      FORWARD_OPENCL
      FORWARD_OPENGL
      FORWARD_VULKAN
      type
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNImageProcess {
        {static} + convertBitmap()
        {static} + convertBuffer()
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNImageProcess.Config {
        + mean : float[]
        + normal : float[]
    }
  }
  

  namespace com.taobao.android.mnn {
    enum Filter {
      BICUBIC
      BILINEAL
      NEAREST
      type
    }
  }
  

  namespace com.taobao.android.mnn {
    enum Format {
      BGR
      BGRA
      GRAY
      RGB
      RGBA
      YUV_420
      YUV_NV21
      type
    }
  }
  

  namespace com.taobao.android.mnn {
    enum Wrap {
      CLAMP_TO_EDGE
      REPEAT
      ZERO
      type
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNNetInstance {
        {static} - TAG : String
        - mNetInstance : long
        {static} + createFromFile()
        + createSession()
        + release()
        - MNNNetInstance()
        - checkValid()
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNNetInstance.Config {
        + forwardType : int
        + numThread : int
        + outputTensors : String[]
        + saveTensors : String[]
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNNetInstance.Session {
        - mSessionInstance : long
        + getInput()
        + getOutput()
        + release()
        + reshape()
        + run()
        + runWithCallback()
        - Session()
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNNetInstance.Session.Tensor {
        - mData : float[]
        - mIntData : int[]
        - mTensorInstance : long
        - mUINT8Data : byte[]
        + getData()
        + getDimensions()
        + getFloatData()
        + getIntData()
        + getUINT8Data()
        + reshape()
        + setInputFloatData()
        + setInputIntData()
        # instance()
        - Tensor()
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNNetNative {
        {static} # nativeConvertBitmapToTensor()
        {static} # nativeConvertBufferToTensor()
        {static} # nativeCreateNetFromFile()
        {static} # nativeCreateSession()
        {static} # nativeGetSessionInput()
        {static} # nativeGetSessionOutput()
        {static} # nativeReleaseNet()
        {static} # nativeReleaseSession()
        {static} # nativeReshapeSession()
        {static} # nativeReshapeTensor()
        {static} # nativeRunSession()
        {static} # nativeRunSessionWithCallback()
        {static} # nativeSetInputFloatData()
        {static} # nativeSetInputIntData()
        {static} # nativeTensorGetData()
        {static} # nativeTensorGetDimensions()
        {static} # nativeTensorGetIntData()
        {static} # nativeTensorGetUINT8Data()
    }
  }
  

  namespace com.taobao.android.mnn {
    class com.taobao.android.mnn.MNNPortraitNative {
        {static} + nativeConvertMaskToPixelsMultiChannels()
    }
  }
  

  com.taobao.android.mnn.MNNImageProcess +-down- com.taobao.android.mnn.MNNImageProcess.Config
  com.taobao.android.mnn.MNNImageProcess +-down- com.taobao.android.mnn.MNNImageProcess.Filter
  com.taobao.android.mnn.MNNImageProcess +-down- com.taobao.android.mnn.MNNImageProcess.Format
  com.taobao.android.mnn.MNNImageProcess +-down- com.taobao.android.mnn.MNNImageProcess.Wrap
  com.taobao.android.mnn.MNNImageProcess.Config o-- com.taobao.android.mnn.MNNImageProcess.Format : dest
  com.taobao.android.mnn.MNNImageProcess.Config o-- com.taobao.android.mnn.MNNImageProcess.Filter : filter
  com.taobao.android.mnn.MNNImageProcess.Config o-- com.taobao.android.mnn.MNNImageProcess.Format : source
  com.taobao.android.mnn.MNNImageProcess.Config o-- com.taobao.android.mnn.MNNImageProcess.Wrap : wrap
  com.taobao.android.mnn.MNNNetInstance +-down- com.taobao.android.mnn.MNNNetInstance.Config
  com.taobao.android.mnn.MNNNetInstance +-down- com.taobao.android.mnn.MNNNetInstance.Session
  com.taobao.android.mnn.MNNNetInstance.Session +-down- com.taobao.android.mnn.MNNNetInstance.Session.Tensor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
